### ISSUE TITLE
andorid 12 not work

### ISSUE THREAD

**Issue by Sev73n** [kleo/switchroot-android-joystick#1]
i uesd [joycon-disable-right-joystick.zip](https://github.com/kleo/switchroot-android-joycon/releases/download/2021.11/joycon-disable-right-joystick.zip) for my xiaomi11 miui13 based andorid 12

right joystick not work in chiaki(ps steamgame software) or moonlight

some butten (L2\R1) error 

![1d8364d567617061f477766d24abf39](https://user-images.githubusercontent.com/16495885/165335690-9f73ba48-d24e-4d0d-b4d8-ebeae14c872f.jpg)

something worng?

**Comment by kleo** [comment]
This is only works for switchroot android
